<a href="https://colab.research.google.com/github/smathews88/nlp/blob/main/03_NLP_LLM_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Understanding the Difference Between Embedding Layers and Linear Layers**

# **Using nn.Embedding**

In [3]:
import torch;
#suppose 2, 3, 1 are the tokens generated after tokenizing..
idx = torch.tensor([2, 3, 1])
# The number of rows in the embedding matrix can be determined by obtaining the largest token ID + 1.
num_idx = max(idx)+1
# The desired embedding dimension is a hyperparameter
out_dim = 5

#below is a simple embedding layer
torch.manual_seed(42)
embedding = torch.nn.Embedding(num_idx, out_dim)

embedding.weight

Parameter containing:
tensor([[ 1.9269,  1.4873,  0.9007, -2.1055, -0.7581],
        [ 1.0783,  0.8008,  1.6806,  0.3559, -0.6866],
        [-0.4934,  0.2415, -0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957,  0.8034, -0.6216]], requires_grad=True)

In [21]:
#below is the vector representation of training example with ID 1
embedding(torch.tensor(idx))

<ipython-input-21-73c7381ee1a6>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  embedding(torch.tensor(idx))


tensor([[-0.4934,  0.2415, -0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957,  0.8034, -0.6216],
        [ 1.0783,  0.8008,  1.6806,  0.3559, -0.6866]],
       grad_fn=<EmbeddingBackward0>)

# **Using nn.Linear**

In [5]:
#convert token IDs into one hot encoding
onehot = torch.nn.functional.one_hot(idx)
onehot

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

In [9]:
torch.manual_seed(42)
linear = torch.nn.Linear(num_idx, out_dim, bias=False)
linear.weight = torch.nn.Parameter(embedding.weight.T.detach())
linear.weight

Parameter containing:
tensor([[ 1.9269,  1.0783, -0.4934,  0.8599],
        [ 1.4873,  0.8008,  0.2415, -0.3097],
        [ 0.9007,  1.6806, -0.2316, -0.3957],
        [-2.1055,  0.3559,  0.0418,  0.8034],
        [-0.7581, -0.6866, -0.2516, -0.6216]], requires_grad=True)

In [17]:
#applying matmul
linear(onehot.float())

tensor([[-0.4934,  0.2415, -0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957,  0.8034, -0.6216],
        [ 1.0783,  0.8008,  1.6806,  0.3559, -0.6866]], grad_fn=<MmBackward0>)